<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="4" ignored="20" total="30" passed="5" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-10-12T15:13:43 IST" name="Suite" finished-at="2022-10-12T15:34:20 IST" duration-ms="1237377">
    <groups>
    </groups>
    <test started-at="2022-10-12T15:13:43 IST" name="Test" finished-at="2022-10-12T15:34:20 IST" duration-ms="1237377">
      <class name="com.marketo.qa.Tests.FetchLeadsCount">
        <test-method signature="CollectLeadsCount()[pri:0, instance:com.marketo.qa.Tests.FetchLeadsCount@4d722ac9]" started-at="2022-10-12T15:24:41 IST" name="CollectLeadsCount" finished-at="2022-10-12T15:28:32 IST" duration-ms="231239" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CollectLeadsCount -->
      </class> <!-- com.marketo.qa.Tests.FetchLeadsCount -->
      <class name="com.marketo.qa.Tests.FetchCampaignCounts">
        <test-method is-config="true" signature="clearScreenshots()[pri:0, instance:com.marketo.qa.Tests.FetchCampaignCounts@4983159f]" started-at="2022-10-12T15:13:43 IST" name="clearScreenshots" finished-at="2022-10-12T15:13:43 IST" duration-ms="24" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearScreenshots -->
        <test-method is-config="true" signature="initialization()[pri:0, instance:com.marketo.qa.Tests.FetchCampaignCounts@4983159f]" started-at="2022-10-12T15:13:43 IST" name="initialization" finished-at="2022-10-12T15:14:12 IST" duration-ms="29546" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method signature="CampaignsCount()[pri:0, instance:com.marketo.qa.Tests.FetchCampaignCounts@4983159f]" started-at="2022-10-12T15:14:12 IST" name="CampaignsCount" finished-at="2022-10-12T15:18:38 IST" duration-ms="266107" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CampaignsCount -->
        <test-method is-config="true" signature="BackToMyMarketo()[pri:0, instance:com.marketo.qa.Tests.FetchCampaignCounts@4983159f]" started-at="2022-10-12T15:34:19 IST" name="BackToMyMarketo" finished-at="2022-10-12T15:34:20 IST" duration-ms="597" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BackToMyMarketo -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.marketo.qa.Tests.FetchCampaignCounts@4983159f]" started-at="2022-10-12T15:34:20 IST" name="teardown" finished-at="2022-10-12T15:34:22 IST" duration-ms="2005" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.marketo.qa.Tests.FetchCampaignCounts -->
      <class name="com.marketo.qa.Tests.FetchNuture_EventCount">
        <test-method signature="ChampiensCount()[pri:0, instance:com.marketo.qa.Tests.FetchNuture_EventCount@2320fa6f]" started-at="2022-10-12T15:22:01 IST" name="ChampiensCount" finished-at="2022-10-12T15:24:41 IST" duration-ms="160273" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ChampiensCount -->
      </class> <!-- com.marketo.qa.Tests.FetchNuture_EventCount -->
      <class name="com.marketo.qa.Tests.FetchModelsCount">
        <test-method signature="ModelCount()[pri:0, instance:com.marketo.qa.Tests.FetchModelsCount@6b53bcc2]" started-at="2022-10-12T15:19:35 IST" name="ModelCount" finished-at="2022-10-12T15:22:01 IST" duration-ms="146019" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ModelCount -->
      </class> <!-- com.marketo.qa.Tests.FetchModelsCount -->
      <class name="com.marketo.qa.Tests.FetchAdminDatas">
        <test-method signature="VerifyCountAndScreenshot()[pri:0, instance:com.marketo.qa.Tests.FetchAdminDatas@3724af13]" started-at="2022-10-12T15:18:38 IST" name="VerifyCountAndScreenshot" finished-at="2022-10-12T15:19:35 IST" duration-ms="56428" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyCountAndScreenshot -->
      </class> <!-- com.marketo.qa.Tests.FetchAdminDatas -->
      <class name="com.marketo.qa.Tests.FetchDesignStudioData">
        <test-method retried="true" signature="TakeRequiredCount()[pri:0, instance:com.marketo.qa.Tests.FetchDesignStudioData@77a7cf58]" started-at="2022-10-12T15:28:32 IST" name="TakeRequiredCount" finished-at="2022-10-12T15:31:21 IST" duration-ms="168606" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
ACT-SS Workspace is not available expected [true] but found [false],
.Customer Support New Hire Workspace Workspace is not available expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
ACT-SS Workspace is not available expected [true] but found [false],
.Customer Support New Hire Workspace Workspace is not available expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.marketo.qa.Pages.DesignStudioPage.SpecificWorkspaceRequiredCount(DesignStudioPage.java:333)
at com.marketo.qa.Tests.FetchDesignStudioData.TakeRequiredCount(FetchDesignStudioData.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TakeRequiredCount -->
        <test-method retried="true" signature="TakeRequiredCount()[pri:0, instance:com.marketo.qa.Tests.FetchDesignStudioData@77a7cf58]" started-at="2022-10-12T15:31:21 IST" name="TakeRequiredCount" finished-at="2022-10-12T15:32:06 IST" duration-ms="44708" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
ACT-SS Workspace is not available expected [true] but found [false],
.Customer Support New Hire Workspace Workspace is not available expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
ACT-SS Workspace is not available expected [true] but found [false],
.Customer Support New Hire Workspace Workspace is not available expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.marketo.qa.Pages.DesignStudioPage.SpecificWorkspaceRequiredCount(DesignStudioPage.java:333)
at com.marketo.qa.Tests.FetchDesignStudioData.TakeRequiredCount(FetchDesignStudioData.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TakeRequiredCount -->
        <test-method retried="true" signature="TakeRequiredCount()[pri:0, instance:com.marketo.qa.Tests.FetchDesignStudioData@77a7cf58]" started-at="2022-10-12T15:32:06 IST" name="TakeRequiredCount" finished-at="2022-10-12T15:32:50 IST" duration-ms="44574" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
ACT-SS Workspace is not available expected [true] but found [false],
.Customer Support New Hire Workspace Workspace is not available expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
ACT-SS Workspace is not available expected [true] but found [false],
.Customer Support New Hire Workspace Workspace is not available expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.marketo.qa.Pages.DesignStudioPage.SpecificWorkspaceRequiredCount(DesignStudioPage.java:333)
at com.marketo.qa.Tests.FetchDesignStudioData.TakeRequiredCount(FetchDesignStudioData.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TakeRequiredCount -->
        <test-method retried="true" signature="TakeRequiredCount()[pri:0, instance:com.marketo.qa.Tests.FetchDesignStudioData@77a7cf58]" started-at="2022-10-12T15:32:50 IST" name="TakeRequiredCount" finished-at="2022-10-12T15:33:35 IST" duration-ms="44491" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
ACT-SS Workspace is not available expected [true] but found [false],
.Customer Support New Hire Workspace Workspace is not available expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
ACT-SS Workspace is not available expected [true] but found [false],
.Customer Support New Hire Workspace Workspace is not available expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.marketo.qa.Pages.DesignStudioPage.SpecificWorkspaceRequiredCount(DesignStudioPage.java:333)
at com.marketo.qa.Tests.FetchDesignStudioData.TakeRequiredCount(FetchDesignStudioData.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TakeRequiredCount -->
        <test-method signature="TakeRequiredCount()[pri:0, instance:com.marketo.qa.Tests.FetchDesignStudioData@77a7cf58]" started-at="2022-10-12T15:33:35 IST" name="TakeRequiredCount" finished-at="2022-10-12T15:34:19 IST" duration-ms="44483" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
ACT-SS Workspace is not available expected [true] but found [false],
.Customer Support New Hire Workspace Workspace is not available expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
ACT-SS Workspace is not available expected [true] but found [false],
.Customer Support New Hire Workspace Workspace is not available expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.marketo.qa.Pages.DesignStudioPage.SpecificWorkspaceRequiredCount(DesignStudioPage.java:333)
at com.marketo.qa.Tests.FetchDesignStudioData.TakeRequiredCount(FetchDesignStudioData.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TakeRequiredCount -->
      </class> <!-- com.marketo.qa.Tests.FetchDesignStudioData -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
